### ISSUE TITLE
version `GLIBC_2.27' not found

### ISSUE THREAD

**Issue by jasonlbx13** [qiuyu96/CoDeF#64]
你好，在进行示例样本生成视频测试的时候，报了如下错误，请问是否是因为此程序只支持ubuntu20.04(我的是18.04)?谢谢！

Traceback (most recent call last):
  File "/home/data/liboxian/codef/train.py", line 19, in <module>
    from models.implicit_model import TranslationField
  File "/home/data/liboxian/codef/models/implicit_model.py", line 4, in <module>
    import tinycudann as tcnn
  File "/home/liboxian/miniconda3/envs/codef/lib/python3.10/site-packages/tinycudann/__init__.py", line 9, in <module>
    from tinycudann.modules import free_temporary_memory, NetworkWithInputEncoding, Network, Encoding
  File "/home/liboxian/miniconda3/envs/codef/lib/python3.10/site-packages/tinycudann/modules.py", line 51, in <module>
    _C = importlib.import_module(f"tinycudann_bindings._{cc}_C")
  File "/home/liboxian/miniconda3/envs/codef/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /home/liboxian/miniconda3/envs/codef/lib/python3.10/site-packages/tinycudann_bindings/_75_C.cpython-310-x86_64-linux-gnu.so)

**Comment by ken-ouyang** [comment]
It seems to be a tinycuda issue. You can try to find the related issues in their repo. I suppose 18.04 is also supported.
